server:
   port: 443
   ssl:
      key-store: keystore.p12
      key-store-password: kl0ft
      keyStoreType: PKCS12
      keyAlias: tomcat
spring:
  application:
    name : recording-service
    
  datasource:
    url : ${datasource.url}
    username : ${datasource.username}
    password : ${datasource.password}
  jpa:
    properties:
      hibernate:
        dialect: ${datasource.dialect}
        connection:
          characterEncoding: UTF-8
          CharSet: UTF-8
          useUnicode: true
    show-sql: true
    hibernate:
      ddl-auto: none